In [3]:
import cv2
import numpy as np
import glob

#Define the 3D world coordinates of the calibration points
object_points = np.zeros((9*6, 3), np.float32)
object_points[:, :2] = np.mgrid[0:9, 0:6].T.reshape(-1, 2)

#Create an empty list to store the 3D world coordinates of the calibration points
object_points_list = []

#Create an empty list to store the 2D image coordinates of the calibration points
image_points_list = []

#Load the calibration images
images = glob.glob('calibration*.jpg')

#Loop over the calibration images
for image in images:
    # Load the image
    img = cv2.imread(image)
    
    #Convert the image to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(gray, (9, 6), None)
    
    #If the corners are found, add the 3D world coordinates and 2D image coordinates to the lists
    if ret == True:
        object_points_list.append(object_points)
        image_points_list.append(corners)
        
#Calibrate the camera
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(object_points_list, image_points_list, gray.shape[::-1], None, None)

#Print the camera matrix and distortion coefficients
print("Camera matrix:\n", mtx)
print("Distortion coefficients:\n", dist)
print(" Rotation Vectors:\n", rvecs) 
print("\n Translation Vectors:\n", t_vecs) 


Camera matrix:
 [[646.42701259   0.         359.88090371]
 [  0.         663.8486536  147.88928206]
 [  0.           0.           1.        ]]
Distortion coefficients:
 [[-1.03437323  1.28232164  0.01723735 -0.06131223 -2.60030793]]
 Rotation Vectors:
 (array([[-0.21712764],
       [-0.17440427],
       [-0.02385925]]),)

 Translation Vectors:
 (array([[-5.80838453],
       [ 2.49947935],
       [14.30476472]]),)
